### ISSUE TITLE
grok filter support

### ISSUE THREAD

**Issue by fbalicchia** [sematext/logagent-js#103]
Hi,
I'll start to think to add grok support to Logagent and my attention is fall on node-grok. During evaluation  and starting [coding](https://github.com/fbalicchia/logagent-js/blob/master/lib/plugins/input-filter/grok.js )  and  I saw that it depends from Oniguruma that is native library that may cause install issue on Windows as indicated [on](https://github.com/Beh01der/node-grok/issues/15) 
I was wondering if that library can be used on Logagent or is necessary find other way ? 
WDYT ?

Thank you in advance

**Comment by otisg** [comment]
I think we already faced a similar situation with the Kafka plugins, but in the end picked something in pure JS, right?  I think @megastef had dealt with this sort of situation before and may be able to suggest how to handle this here.

**Comment by megastef** [comment]
Right - we checked some option already. We used Node native regex because it is very fast and portable. 
See e.g. 
- https://github.com/slevithan/xregexp/issues/140
- https://github.com/rsyslog/liblognorm/issues/112  (liblognorm is very efficient and used in rsyslog)

The "new" plugin architecture might offer alternative ways to hook in alternative parsers (e.g. as input-filter plugin, which could emit JSON strings to LA processing chain after parsing text with an alternative parser). Windows is less a problem as long the native libraries are available as pre-compiled windows modules, which needs to be checked before we add new libraries to Logagent core. 

From the architecture point of view, it would be interesting to have an option to support multiple regex/parsing rules based on different libraries. We will need some time to see the best way to broaden support for parser libraries.

**Comment by fbalicchia** [comment]
thanks @megastef  for sharing

**Comment by fbalicchia** [comment]
Hi @megastef ,
I thougth to a possible solution for a new input-filter-pluging. 

When input publish **data.raw** instead to go directly in filter function like now, [link](https://github.com/sematext/logagent-js/blob/master/bin/logagent.js#L277)
messages they might go in new function where is possible apply some logic or method present in the new module, in this case for example grok. 
After message is "transform" is possible to publish it on emitter and so that it is captured by the old filter method. 
Cutting messages logic and so on remains in the same place, in the yml file we can instruct logagent to load input-filter-module with that key **input-filter-module**

Am I on the right way or I've missing something ?

**Comment by otisg** [comment]
Are you referring to something like #43, @fbalicchia ?

**Comment by fbalicchia** [comment]
Hi,
my idea was that, but for this issue after some check I thought that was out of scope.
In pr I have extends input filter function for manage directly if necessary event. In the same
commit I've refactor all input plugins to use LogEventEmitter that IMHO seems I thought for manage in one point all event definitions.

To avoid native dependency in logagent core I've created a plugin as usual.
https://github.com/fbalicchia/logagent-input-filter-grok

thanks for tips again
