### ISSUE TITLE
Error while installing logagent

### ISSUE THREAD

**Issue by murarisumit** [sematext/logagent-js#120]
`sudo npm i -g @sematext/logagent` was failing with below error message.

```
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/@sematext/logagent/node_modules/zmq/.node-gyp"
make: Entering directory '/usr/lib/node_modules/@sematext/logagent/node_modules/zmq/build'
  CXX(target) Release/obj.target/zmq/binding.o
../binding.cc:28:17: fatal error: zmq.h: No such file or directory
compilation terminated.
```

`sudo apt install libzmq-dev` solved this, is it normal step of installing. Should we add this in documentation.

**Comment by megastef** [comment]
I don‘t see a dependency to ZeroMQ in package.json. The ZeroMQ plugins are 3rd party plugin. Did you install one of the ZMQ plugins? 

Could you please try again to install the latest version of Logagent? 

‚sudo npm i -g @sematext/logagent@latest‘

**Comment by megastef** [comment]
@murarisumit please note there was an indirect dependency to ZeroMQ by the optionally installed MQTT broker Mosca. I think the error was shown, but npm should not fail because of the missing ZeroMQ lib. Anyhow, we replaced Mosca MQTT lib and installation should work without ZeroMQ.  

Please try `sudo npm i -g @sematext/logagent@2.0.101`

**Comment by murarisumit** [comment]
Thanks @megastef. Got it, it worked fine now :)
