### ISSUE TITLE
Elasticsearch support

### ISSUE THREAD

**Issue by devnullsp** [sematext/logagent-js#19]
Thanks at first.

Ok, elasticsearch is supported, but any example? who i do output to my private elascticsearch sever?

TIA

**Comment by megastef** [comment]
Please see: [Documentation](http://sematext.github.io/logagent-js/cli-parameters/) for CLI parameters.

```
logagent -e http://localhost:9200 --index YourIndex --print_stats 30 -g '/var/log/**/*.log'
```

Tails all logs from /var/log/**/*.log, and ships it to local ES cluster to YourIndex, prints success/failed http req stats. Output of parsed logs to console is suppressed (-s) .  

Instead of -e  you could set an environment variable LOGSENE_URL=http://localhost:9200. 

We are in preparation for log routing to multiple indices https://github.com/sematext/logagent-js/issues/11, but this is not yet released to npm (yet).

**Comment by megastef** [comment]
I would also recommend to set ```--logsene-tmp-dir /tmp```  - to store files, when Elasticsearch is not available. 

Please note logagent is using logsene-js, so all env vars from there could be applied (like size of bulk requests) : https://www.npmjs.com/package/logsene-js
```
export LOGSENE_LOG_INTERVAL=10000 # send bulk every 10 seconds, or when max bulk size is reached
export LOGSENE_BULK_SIZE=1000          # max number of docs per bulk
export LOGSENE_BULK_SIZE_BYTES=5242880  # max bulk size in bytes 5 MB
export MAX_CLIENT_SOCKETS=2  # maximum number of sockets for http connection pool
Note: Set this to a low value because node.js might open too many Elasticsearch http connections (ASYNC I/O) and Elasticsearch might reject http connections then.
```

**Comment by megastef** [comment]
@devnullsp  Did it work with your Elasticsearch? Closing this issue.

**Comment by devnullsp** [comment]
Sorry for dealy, but yes this work!.

Thanks.
