### ISSUE TITLE
Implement Filebeat input

### ISSUE THREAD

**Issue by otisg** [sematext/logagent-js#27]
So one can use Logagent in place of Logstash, for example.

**Comment by megastef** [comment]
Supposed to be a plugin, after having the framework, see https://github.com/sematext/logagent-js/issues/28

**Comment by megastef** [comment]
Which network protocol and message format is used by https://github.com/logstash-plugins/logstash-input-beats?

**Comment by radu-gheorghe** [comment]
While one could look [here](https://github.com/logstash-plugins/logstash-input-beats/tree/master/src/main/java/org/logstash/beats) and reverse-engineer how it work, the protocol is not defined yet and still evolving (as mentioned [here](https://github.com/elastic/go-lumber/issues/1#issuecomment-257786505) - where you can see a work-in-progress spec of the protocol).

I would actually reframe this issue and, instead of supporting the beats protocol, support the Elasticsearch bulk API for ingestion. This will not only add support for Filebeat and all other beats, but for any shipper that can push data to Elasticsearch.

**Comment by otisg** [comment]
Closing in favour of #52.
